### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Grimler91** [VDavid003/minimal_sboot_wrapper#1]
Hi there!

Is this project released under any particular license?

**Comment by VDavid003** [comment]
Hi, I did not specify a license because I did not know what the inclusion of the Linux kernel inside allows me to do. You are free to do whatever you want with it as long as I am not responsible for anything and it conforms to any limitations having the kernel linked causes.

**Comment by Grimler91** [comment]
Good point, I suppose GPL-2.0 might apply if it is compiled and distributed, but I am not a lawyer.

Thanks for the info.
